In [37]:
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_info_columns', 200)

In [38]:
gcbs_df = pd.read_csv('openpsychometrics_gcbs_data.csv')

In [39]:
gcbs_df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Q1,5,5,2,5,5,1,4,5,1,1
Q2,5,5,4,4,4,1,3,4,1,2
Q3,3,5,1,1,1,1,3,3,1,1
Q4,5,5,2,2,4,1,3,3,1,1
Q5,5,5,2,4,4,1,4,4,1,1
Q6,5,3,2,5,5,1,3,5,1,5
Q7,5,5,4,4,4,1,3,5,1,1
Q8,3,5,2,1,3,1,4,5,1,1
Q9,4,1,2,4,1,1,2,5,1,1
Q10,5,4,4,5,5,1,3,5,1,4
Q11,5,4,2,5,5,1,3,5,1,1
Q12,5,5,4,5,5,1,2,5,1,1
Q13,3,4,0,1,3,1,2,3,1,1
Q14,5,4,2,4,5,1,3,4,1,1
Q15,5,5,4,5,5,1,4,5,1,5
E1,7070,4086,27535,4561,8841,15267,7249,8024,4654,23787
E2,7469,13107,7814,5589,7575,7112,4651,7343,6076,12375
E3,7383,2807,7762,3506,3832,4798,5496,6808,3032,2006
E4,6540,5030,10290,3784,7775,5214,3936,6794,3984,3650
E5,9098,7405,8558,5093,4160,3683,7831,8743,4328,3188
E6,4998,7864,10538,3555,5216,4130,6816,6196,4070,48851
E7,6971,16234,4740,3158,7559,4487,6167,7762,4012,9013
E8,4713,2603,4162,1887,5792,2376,2032,4797,2430,2128
E9,6032,14174,6492,7678,10296,3273,4000,8015,4191,2898
E10,5878,9423,11512,2304,5455,5501,3583,5764,8444,10420
E11,4031,11683,6874,3604,3864,3790,4481,5717,4224,5820
E12,4386,12718,11440,2724,11799,7777,5071,5352,4404,2049
E13,9077,4816,0,2689,7872,4553,2368,6387,1065,9901
E14,5113,6806,11418,2657,10543,5944,4408,9671,5533,3838
E15,4204,4823,9872,3824,4224,4028,6103,5622,4964,7208
introelapse,11,6,7,5,4,35,12,27,2,26
testelapse,95,125,141,58,105,87,75,104,67,148
surveyelapse,142,144,90,135,210,154,67,186,121,118
TIPI1,5,6,6,6,1,4,2,4,4,1
TIPI2,3,7,6,7,3,2,5,5,5,6
TIPI3,6,6,6,7,7,6,4,6,6,3
TIPI4,2,7,1,5,2,2,2,2,2,1
TIPI5,6,6,7,7,6,6,5,7,4,5
TIPI6,6,3,5,6,4,5,6,4,5,7
TIPI7,7,7,6,5,5,6,2,5,6,6
TIPI8,2,5,5,1,5,3,3,5,2,5
TIPI9,7,1,7,5,5,6,5,3,7,7
TIPI10,1,1,7,1,3,2,5,1,2,4
VCL1,1,1,1,1,1,1,1,1,1,1
VCL2,1,1,1,1,1,1,1,1,1,1
VCL3,1,0,1,1,0,1,0,0,0,1
VCL4,1,1,1,1,1,1,1,1,1,1
VCL5,1,1,1,1,1,1,1,1,1,1
VCL6,0,0,1,0,0,0,0,0,0,0
VCL7,0,0,1,0,0,0,0,0,0,0
VCL8,0,0,1,1,0,0,0,0,0,0
VCL9,0,0,0,0,0,1,0,0,0,0
VCL10,1,1,1,1,1,1,1,1,1,1
VCL11,1,1,1,1,0,1,0,0,0,0
VCL12,0,0,0,0,0,1,0,0,0,0
VCL13,1,0,1,1,1,1,1,0,1,1
VCL14,1,1,1,1,1,1,1,1,1,1
VCL15,1,1,1,0,1,1,1,1,1,1
VCL16,1,1,1,1,1,1,1,1,1,1
education,3,1,4,3,2,3,2,2,1,3
urban,0,2,2,1,2,1,2,1,3,3
gender,1,2,2,1,1,1,1,1,1,1
engnat,2,1,2,1,1,1,1,1,1,2
age,28,14,26,25,37,34,17,23,17,28
hand,1,1,1,1,1,1,1,1,1,1
religion,2,1,1,12,2,7,1,2,4,2
orientation,1,2,1,1,2,1,1,1,2,1
race,5,4,4,4,4,4,4,4,4,4
voted,2,2,1,1,2,1,2,2,2,1
married,1,1,1,1,2,2,1,1,1,2
familysize,1,1,2,3,2,2,2,3,2,3
major,ACTING,NaN,philosophy,history,Psychology,nursing,NaN,NaN,NaN,it

In [40]:
gcbs_df.info(max_cols=100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2495 entries, 0 to 2494
Data columns (total 72 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Q1            2495 non-null   int64
 1   Q2            2495 non-null   int64
 2   Q3            2495 non-null   int64
 3   Q4            2495 non-null   int64
 4   Q5            2495 non-null   int64
 5   Q6            2495 non-null   int64
 6   Q7            2495 non-null   int64
 7   Q8            2495 non-null   int64
 8   Q9            2495 non-null   int64
 9   Q10           2495 non-null   int64
 10  Q11           2495 non-null   int64
 11  Q12           2495 non-null   int64
 12  Q13           2495 non-null   int64
 13  Q14           2495 non-null   int64
 14  Q15           2495 non-null   int64
 15  E1            2495 non-null   int64
 16  E2            2495 non-null   int64
 17  E3            2495 non-null   int64
 18  E4            2495 non-null   int64
 19  E5            2495 non-null   int64
 20  E6            2495 non-null   int64
 21  E7            2495 non-null   int64
 22  E8            2495 non-null   int64
 23  E9            2495 non-null   int64
 24  E10           2495 non-null   int64
 25  E11           2495 non-null   int64
 26  E12           2495 non-null   int64
 27  E13           2495 non-null   int64
 28  E14           2495 non-null   int64
 29  E15           2495 non-null   int64
 30  introelapse   2495 non-null   int64
 31  testelapse    2495 non-null   int64
 32  surveyelapse  2495 non-null   int64
 33  TIPI1         2495 non-null   int64
 34  TIPI2         2495 non-null   int64
 35  TIPI3         2495 non-null   int64
 36  TIPI4         2495 non-null   int64
 37  TIPI5         2495 non-null   int64
 38  TIPI6         2495 non-null   int64
 39  TIPI7         2495 non-null   int64
 40  TIPI8         2495 non-null   int64
 41  TIPI9         2495 non-null   int64
 42  TIPI10        2495 non-null   int64
 43  VCL1          2495 non-null   int64
 44  VCL2          2495 non-null   int64
 45  VCL3          2495 non-null   int64
 46  VCL4          2495 non-null   int64
 47  VCL5          2495 non-null   int64
 48  VCL6          2495 non-null   int64
 49  VCL7          2495 non-null   int64
 50  VCL8          2495 non-null   int64
 51  VCL9          2495 non-null   int64
 52  VCL10         2495 non-null   int64
 53  VCL11         2495 non-null   int64
 54  VCL12         2495 non-null   int64
 55  VCL13         2495 non-null   int64
 56  VCL14         2495 non-null   int64
 57  VCL15         2495 non-null   int64
 58  VCL16         2495 non-null   int64
 59  education     2495 non-null   int64
 60  urban         2495 non-null   int64
 61  gender        2495 non-null   int64
 62  engnat        2495 non-null   int64
 63  age           2495 non-null   int64
 64  hand          2495 non-null   int64
 65  religion      2495 non-null   int64
 66  orientation   2495 non-null   int64
 67  race          2495 non-null   int64
 68  voted         2495 non-null   int64
 69  married       2495 non-null   int64
 70  familysize    2495 non-null   int64
 71  major         1337 non-null   object
dtypes: int64(71), object(1)
memory usage: 1.4+ MB